# Generated by Django 4.2.3 on 2023-11-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateField()),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('veterinarian', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('vaccine_card', models.ImageField(upload_to='')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pets')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.records')),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateField()),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pets')),
            ],
        ),
        migrations.AddField(
            model_name='pets',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.users'),
        ),
    ]
